# This work is released into the Public Domain under the
# terms of the Creative Commons CC0 1.0 Universal license.
# https://creativecommons.org/publicdomain/zero/1.0/

language: java

branches:
  only:
  - travis-ci

dist: xenial
addons:
  apt:
    update: true
    packages:
    - ant
    - ant-contrib
    - ant-optional
    - junit4
    - libhamcrest-java

install:
- cp -v .travis.ant.local ant.local

script:
- ant compile test jdoc
